# Generated by Django 3.2.10 on 2024-01-23 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7f8dd677-be3e-42ee-b5b7-b5a4d4fdb9d0'), editable=False, primary_key=True, serialize=False)),
                ('duration', models.IntegerField(null=True)),
                ('wScore', models.PositiveSmallIntegerField(null=True)),
                ('lScore', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
