# Generated by Django 4.2.6 on 2024-01-08 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('bd57bf0e-176e-47c7-bac4-35ccf02b6a23'), editable=False, primary_key=True, serialize=False)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lostMatches', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wonMatches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
