# Generated by Django 4.2.6 on 2024-01-29 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine', models.CharField(max_length=100, null=True)),
                ('loosers', models.ManyToManyField(blank=True, related_name='loosers', to=settings.AUTH_USER_MODEL)),
                ('matches', models.ManyToManyField(blank=True, related_name='tournaments', to='game.match')),
                ('players', models.ManyToManyField(blank=True, related_name='tournaments', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wonTournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
