# Generated by Django 3.2.10 on 2024-01-11 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.UUIDField(default=uuid.UUID('54cb730b-0b7c-464c-9f72-f4edf68a2b9d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
