# Generated by Django 3.2.10 on 2024-02-14 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4886d62a-791f-43b6-992b-3d6903cafcba'), editable=False, primary_key=True, serialize=False),
        ),
    ]
