# Generated by Django 4.2.6 on 2024-01-12 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.UUIDField(default=uuid.UUID('34bf31b3-b052-4b0d-906d-03b43a0ec5dd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
