# Generated by Django 4.2.6 on 2024-01-22 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_alter_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='lScore',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='wScore',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wonMatches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b9cca551-ddf3-4c60-8f12-a4b851512578'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1Matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2Matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
