version: '3'
services:
  angular-app:
    image: angular-app
    networks:
      - transcendence
    build:
      context: containers/angular
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:4200:4200
    volumes:
      - ./frontend/angular:/var/www/frontend
  
  django-app:
    image: django-app
    networks:
      - transcendence
    build:
      context: containers/django
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./backend/app/back:/var/www/backend
    # healthcheck :
    #   test:  nc -w 5 127.0.0.1 4200
    #   interval: 5s
    #   retries: 30
<<<<<<< Updated upstream
    
    # depends_on:
    #   angular-app:
    #     condition: service_healthy
=======
  
  postgresql:
    container_name: postgresql
    build:
      context: ./containers/postgres/
      dockerfile: Dockerfile
    restart: always
    env_file:
      .env
    networks:
      - transcendence
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: --no-locale --encoding=UTF-8
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - type: bind
        source: ./volumes/db
        target: /var/lib/postgresql/data
    healthcheck:
      test: nc -w 5 127.0.0.1 5432
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "${DB_PORT}:5432"
 
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: on-failure
    networks:
      - transcendence
    env_file:
      .env
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      postgresql:
        condition: service_healthy
>>>>>>> Stashed changes

networks:
   transcendence:
