version: '3.8'

services:
  angular:
    image: angular
    container_name: angular
    networks:
      - transcendence
    build:
      context: containers/angular
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./frontend/angular:/var/www/frontend
    depends_on:
      - django

  django:
    image: django
    container_name: django
    networks:
      - transcendence
    build:
      context: containers/django
      dockerfile: Dockerfile
    env_file:
      .env
    ports:
      - 8000:8000
    volumes:
      - ./backend/app/back:/var/www/backend
    depends_on:
      postgresql:
        condition: service_healthy
    # healthcheck :
    #   test:  nc -w 5 127.0.0.1 4200
    #   interval: 5s
    #   retries: 30
    
    # depends_on:
    #   angular-app:
    #     condition: service_healthy

networks:
  transcendence:

volumes:
  db:
