version: '3'
services:
  angular-app:
    image: angular-app
    container_name: angular
    networks:
      - transcendence
    build:
      context: containers/angular
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./frontend/angular:/var/www/frontend
  
  django-app:
    image: django-app
    container_name: django
    networks:
      - transcendence
    build:
      context: containers/django
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend/app/back:/var/www/backend
    # healthcheck :
    #   test:  nc -w 5 127.0.0.1 4200
    #   interval: 5s
    #   retries: 30
    depends_on:
     - redis

  redis: 
    image: redislabs/redismod
    container_name: redis
    networks:
      - transcendence
    ports:
     - 6379:6379

networks:
   transcendence:
