# Generated by Django 4.2.6 on 2023-12-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
