# Generated by Django 4.2.6 on 2024-01-29 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ccfee50c-a7e3-4068-8733-ab6d4673500e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
