# Generated by Django 4.2.6 on 2024-01-23 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.UUID('84984f91-0602-4093-876f-5ce72270fb20'), editable=False, primary_key=True, serialize=False),
        ),
    ]
