# Generated by Django 4.2.6 on 2024-01-23 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.UUID('581a86d8-ec19-4845-a84e-77ed9ac668af'), editable=False, primary_key=True, serialize=False),
        ),
    ]
