# Generated by Django 4.2.6 on 2023-12-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
