# Generated by Django 4.2.6 on 2024-01-22 10:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c7d1a38e-ac87-4fcb-ad8f-2efb5506078a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
