# Generated by Django 3.2.10 on 2024-01-22 17:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.UUID('53e4575b-d66d-4ea5-82a2-9f846d31ca9f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
