# Generated by Django 4.2.6 on 2023-11-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='winMatchesCount',
            new_name='wonMatchesCount',
        ),
    ]
