# Generated by Django 4.2.6 on 2023-11-22 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('wScore', models.PositiveSmallIntegerField()),
                ('lScore', models.PositiveSmallIntegerField()),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lostMatches', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wonMatches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
