# Generated by Django 3.2.10 on 2024-02-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.FileField(blank=True, default='default.jpg', upload_to='avatars'),
        ),
    ]
