# Generated by Django 4.2.6 on 2023-11-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gameRatio',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1),
        ),
    ]
