# Generated by Django 4.2.6 on 2023-11-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_gameratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lostMatchesCount',
            new_name='MatchesCount',
        ),
    ]
