# Generated by Django 4.2.6 on 2023-11-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_gameratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gameRatio',
            field=models.FloatField(default=0.0),
        ),
    ]
