# Generated by Django 4.2.6 on 2023-11-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_gameratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='avatars'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
