# Generated by Django 4.2.6 on 2023-11-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_gameratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lostMatchesCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='winMatchesCount',
            field=models.IntegerField(default=0),
        ),
    ]
